# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(846, 523)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.results_field = QtWidgets.QTextBrowser(Form)
        self.results_field.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.results_field.setReadOnly(True)
        self.results_field.setObjectName("results_field")
        self.gridLayout_2.addWidget(self.results_field, 0, 1, 6, 1)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.line_output = QtWidgets.QLineEdit(self.groupBox)
        self.line_output.setObjectName("line_output")
        self.gridLayout_5.addWidget(self.line_output, 4, 0, 1, 1)
        self.sample_spin = QtWidgets.QSpinBox(self.groupBox)
        self.sample_spin.setMaximum(999)
        self.sample_spin.setProperty("value", 50)
        self.sample_spin.setObjectName("sample_spin")
        self.gridLayout_5.addWidget(self.sample_spin, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_5.addWidget(self.label, 2, 0, 1, 1)
        self.select_output = QtWidgets.QToolButton(self.groupBox)
        self.select_output.setObjectName("select_output")
        self.gridLayout_5.addWidget(self.select_output, 4, 1, 1, 1)
        self.line_input = QtWidgets.QLineEdit(self.groupBox)
        self.line_input.setObjectName("line_input")
        self.gridLayout_5.addWidget(self.line_input, 3, 0, 1, 1)
        self.select_input = QtWidgets.QToolButton(self.groupBox)
        self.select_input.setObjectName("select_input")
        self.gridLayout_5.addWidget(self.select_input, 3, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(Form)
        self.groupBox_7.setObjectName("groupBox_7")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_9 = QtWidgets.QLabel(self.groupBox_7)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        self.weights_box = QtWidgets.QComboBox(self.groupBox_7)
        self.weights_box.setObjectName("weights_box")
        self.weights_box.addItem("")
        self.weights_box.addItem("")
        self.horizontalLayout_3.addWidget(self.weights_box)
        self.lambda_check = QtWidgets.QCheckBox(self.groupBox_7)
        self.lambda_check.setObjectName("lambda_check")
        self.horizontalLayout_3.addWidget(self.lambda_check)
        self.gridLayout_2.addWidget(self.groupBox_7, 1, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(Form)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radio_cheb = QtWidgets.QRadioButton(self.groupBox_3)
        self.radio_cheb.setChecked(True)
        self.radio_cheb.setObjectName("radio_cheb")
        self.verticalLayout.addWidget(self.radio_cheb)
        self.radio_legend = QtWidgets.QRadioButton(self.groupBox_3)
        self.radio_legend.setObjectName("radio_legend")
        self.verticalLayout.addWidget(self.radio_legend)
        self.radio_lagg = QtWidgets.QRadioButton(self.groupBox_3)
        self.radio_lagg.setObjectName("radio_lagg")
        self.verticalLayout.addWidget(self.radio_lagg)
        self.radio_herm = QtWidgets.QRadioButton(self.groupBox_3)
        self.radio_herm.setObjectName("radio_herm")
        self.verticalLayout.addWidget(self.radio_herm)
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 1, 0, 1, 1)
        self.x2_deg = QtWidgets.QSpinBox(self.groupBox_4)
        self.x2_deg.setProperty("value", 7)
        self.x2_deg.setObjectName("x2_deg")
        self.gridLayout_4.addWidget(self.x2_deg, 1, 1, 1, 1)
        self.x3_deg = QtWidgets.QSpinBox(self.groupBox_4)
        self.x3_deg.setProperty("value", 4)
        self.x3_deg.setObjectName("x3_deg")
        self.gridLayout_4.addWidget(self.x3_deg, 2, 1, 1, 1)
        self.x1_deg = QtWidgets.QSpinBox(self.groupBox_4)
        self.x1_deg.setProperty("value", 7)
        self.x1_deg.setObjectName("x1_deg")
        self.gridLayout_4.addWidget(self.x1_deg, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 2, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_4)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 2, 0, 1, 1)
        self.x1_dim = QtWidgets.QSpinBox(self.groupBox_2)
        self.x1_dim.setProperty("value", 3)
        self.x1_dim.setObjectName("x1_dim")
        self.gridLayout_3.addWidget(self.x1_dim, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.y_dim = QtWidgets.QSpinBox(self.groupBox_2)
        self.y_dim.setProperty("value", 2)
        self.y_dim.setObjectName("y_dim")
        self.gridLayout_3.addWidget(self.y_dim, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 3, 0, 1, 1)
        self.x2_dim = QtWidgets.QSpinBox(self.groupBox_2)
        self.x2_dim.setProperty("value", 1)
        self.x2_dim.setObjectName("x2_dim")
        self.gridLayout_3.addWidget(self.x2_dim, 1, 1, 1, 1)
        self.x3_dim = QtWidgets.QSpinBox(self.groupBox_2)
        self.x3_dim.setProperty("value", 2)
        self.x3_dim.setObjectName("x3_dim")
        self.gridLayout_3.addWidget(self.x3_dim, 2, 1, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.gridLayout_2.addWidget(self.groupBox_5, 2, 0, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(Form)
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.exec_button = QtWidgets.QPushButton(self.groupBox_6)
        self.exec_button.setDefault(True)
        self.exec_button.setFlat(False)
        self.exec_button.setObjectName("exec_button")
        self.horizontalLayout_2.addWidget(self.exec_button)
        self.plot_button = QtWidgets.QPushButton(self.groupBox_6)
        self.plot_button.setObjectName("plot_button")
        self.horizontalLayout_2.addWidget(self.plot_button)
        self.gridLayout_2.addWidget(self.groupBox_6, 3, 0, 3, 1)

        self.retranslateUi(Form)
        self.exec_button.clicked.connect(Form.exec_clicked)
        self.plot_button.clicked.connect(Form.plot_clicked)
        self.sample_spin.valueChanged['int'].connect(Form.samples_modified)
        self.select_input.clicked.connect(Form.input_clicked)
        self.select_output.clicked.connect(Form.output_clicked)
        self.x1_dim.valueChanged['int'].connect(Form.dimension_modified)
        self.x2_dim.valueChanged['int'].connect(Form.dimension_modified)
        self.x3_dim.valueChanged['int'].connect(Form.dimension_modified)
        self.x1_deg.valueChanged['int'].connect(Form.degree_modified)
        self.x2_deg.valueChanged['int'].connect(Form.degree_modified)
        self.x3_deg.valueChanged['int'].connect(Form.degree_modified)
        self.radio_cheb.toggled['bool'].connect(Form.type_modified)
        self.radio_herm.toggled['bool'].connect(Form.type_modified)
        self.radio_lagg.toggled['bool'].connect(Form.type_modified)
        self.radio_legend.toggled['bool'].connect(Form.type_modified)
        Form.output_changed['QString'].connect(self.line_output.setText)
        Form.input_changed['QString'].connect(self.line_input.setText)
        self.line_input.textChanged['QString'].connect(Form.input_modified)
        self.line_output.textChanged['QString'].connect(Form.output_modified)
        self.lambda_check.toggled['bool'].connect(Form.lambda_calc_method_changed)
        self.weights_box.currentIndexChanged['QString'].connect(Form.weights_modified)
        self.y_dim.valueChanged['int'].connect(Form.dimension_modified)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.radio_cheb, self.radio_legend)
        Form.setTabOrder(self.radio_legend, self.radio_lagg)
        Form.setTabOrder(self.radio_lagg, self.radio_herm)
        Form.setTabOrder(self.radio_herm, self.x1_deg)
        Form.setTabOrder(self.x1_deg, self.x2_deg)
        Form.setTabOrder(self.x2_deg, self.x3_deg)
        Form.setTabOrder(self.x3_deg, self.x1_dim)
        Form.setTabOrder(self.x1_dim, self.x2_dim)
        Form.setTabOrder(self.x2_dim, self.x3_dim)
        Form.setTabOrder(self.x3_dim, self.y_dim)
        Form.setTabOrder(self.y_dim, self.sample_spin)
        Form.setTabOrder(self.sample_spin, self.line_input)
        Form.setTabOrder(self.line_input, self.select_input)
        Form.setTabOrder(self.select_input, self.line_output)
        Form.setTabOrder(self.line_output, self.select_output)
        Form.setTabOrder(self.select_output, self.exec_button)
        Form.setTabOrder(self.exec_button, self.plot_button)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form1"))
        self.results_field.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.SF NS Text\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'.Menio Regular\'; font-size:10pt;\"><br /></p></body></html>"))
        self.results_field.setPlaceholderText(_translate("Form", "Результати"))
        self.groupBox.setTitle(_translate("Form", "Дані"))
        self.line_output.setPlaceholderText(_translate("Form", "Вихідний файл"))
        self.label.setText(_translate("Form", "Вибірка:"))
        self.select_output.setText(_translate("Form", "..."))
        self.line_input.setPlaceholderText(_translate("Form", "Вхідний файл"))
        self.select_input.setText(_translate("Form", "..."))
        self.groupBox_7.setTitle(_translate("Form", "Додатково"))
        self.label_9.setText(_translate("Form", "Ваги:"))
        self.weights_box.setItemText(0, _translate("Form", "Average"))
        self.weights_box.setItemText(1, _translate("Form", "Scaled"))
        self.lambda_check.setText(_translate("Form", "3-блочні вирази"))
        self.groupBox_5.setTitle(_translate("Form", "Поліноми"))
        self.groupBox_3.setTitle(_translate("Form", "Типи"))
        self.radio_cheb.setText(_translate("Form", "Чебешева"))
        self.radio_legend.setText(_translate("Form", "Лежандра"))
        self.radio_lagg.setText(_translate("Form", "Лаґерра"))
        self.radio_herm.setText(_translate("Form", "Ерміта"))
        self.groupBox_4.setTitle(_translate("Form", "Степені"))
        self.label_8.setText(_translate("Form", "X2"))
        self.label_7.setText(_translate("Form", "X3"))
        self.label_6.setText(_translate("Form", "X1"))
        self.groupBox_2.setTitle(_translate("Form", "Розмірність"))
        self.label_4.setText(_translate("Form", "X3"))
        self.label_2.setText(_translate("Form", "X1"))
        self.label_3.setText(_translate("Form", "X2"))
        self.label_5.setText(_translate("Form", "Y"))
        self.groupBox_6.setTitle(_translate("Form", "Обробка"))
        self.exec_button.setText(_translate("Form", "Порахувати"))
        self.plot_button.setText(_translate("Form", "Намалювати"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

